// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { blogPostId, type BlogPostId } from './BlogPost';
import {
  blogPostCategoryId,
  type BlogPostCategoryId,
} from './BlogPostCategory';
import { z } from 'zod';

/** Represents the table public.blog_post_blog_post_category */
export default interface BlogPostBlogPostCategory {
  blog_post_id: BlogPostId;

  blog_post_category_id: BlogPostCategoryId;
}

/** Represents the initializer for the table public.blog_post_blog_post_category */
export interface BlogPostBlogPostCategoryInitializer {
  blog_post_id: BlogPostId;

  blog_post_category_id: BlogPostCategoryId;
}

/** Represents the mutator for the table public.blog_post_blog_post_category */
export interface BlogPostBlogPostCategoryMutator {
  blog_post_id?: BlogPostId;

  blog_post_category_id?: BlogPostCategoryId;
}

export const blogPostBlogPostCategory = z.object({
  blog_post_id: blogPostId,
  blog_post_category_id: blogPostCategoryId,
}) as unknown as z.Schema<BlogPostBlogPostCategory>;

export const blogPostBlogPostCategoryInitializer = z.object({
  blog_post_id: blogPostId,
  blog_post_category_id: blogPostCategoryId,
}) as unknown as z.Schema<BlogPostBlogPostCategoryInitializer>;

export const blogPostBlogPostCategoryMutator = z.object({
  blog_post_id: blogPostId.optional(),
  blog_post_category_id: blogPostCategoryId.optional(),
}) as unknown as z.Schema<BlogPostBlogPostCategoryMutator>;
