// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Identifier type for public.blog_post_status */
export type BlogPostStatusId = string & { __brand: 'BlogPostStatusId' };

/** Represents the table public.blog_post_status */
export default interface BlogPostStatus {
  id: BlogPostStatusId;

  identifier: string;

  label: string;

  x_created: Date;
}

/** Represents the initializer for the table public.blog_post_status */
export interface BlogPostStatusInitializer {
  /** Default value: uuid_generate_v4() */
  id?: BlogPostStatusId;

  identifier: string;

  label: string;

  /** Default value: CURRENT_TIMESTAMP */
  x_created?: Date;
}

/** Represents the mutator for the table public.blog_post_status */
export interface BlogPostStatusMutator {
  id?: BlogPostStatusId;

  identifier?: string;

  label?: string;

  x_created?: Date;
}

export const blogPostStatusId =
  z.string() as unknown as z.Schema<BlogPostStatusId>;

export const blogPostStatus = z.object({
  id: blogPostStatusId,
  identifier: z.string(),
  label: z.string(),
  x_created: z.date(),
}) as unknown as z.Schema<BlogPostStatus>;

export const blogPostStatusInitializer = z.object({
  id: blogPostStatusId.optional(),
  identifier: z.string(),
  label: z.string(),
  x_created: z.date().optional(),
}) as unknown as z.Schema<BlogPostStatusInitializer>;

export const blogPostStatusMutator = z.object({
  id: blogPostStatusId.optional(),
  identifier: z.string().optional(),
  label: z.string().optional(),
  x_created: z.date().optional(),
}) as unknown as z.Schema<BlogPostStatusMutator>;
