// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Identifier type for public.migrations */
export type MigrationsId = string & { __brand: 'MigrationsId' };

/** Represents the table public.migrations */
export default interface Migrations {
  id: MigrationsId;

  created_at: Date | null;
}

/** Represents the initializer for the table public.migrations */
export interface MigrationsInitializer {
  id: MigrationsId;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;
}

/** Represents the mutator for the table public.migrations */
export interface MigrationsMutator {
  id?: MigrationsId;

  created_at?: Date | null;
}

export const migrationsId = z.string() as unknown as z.Schema<MigrationsId>;

export const migrations = z.object({
  id: migrationsId,
  created_at: z.date().nullable(),
}) as unknown as z.Schema<Migrations>;

export const migrationsInitializer = z.object({
  id: migrationsId,
  created_at: z.date().optional().nullable(),
}) as unknown as z.Schema<MigrationsInitializer>;

export const migrationsMutator = z.object({
  id: migrationsId.optional(),
  created_at: z.date().optional().nullable(),
}) as unknown as z.Schema<MigrationsMutator>;
