// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { userProfileId, type UserProfileId } from './UserProfile';
import { z } from 'zod';

/** Identifier type for public.session */
export type SessionId = string & { __brand: 'SessionId' };

/** Represents the table public.session */
export default interface Session {
  id: SessionId;

  user_id: UserProfileId;

  token: string;

  valid_until: Date;

  created_at: Date;
}

/** Represents the initializer for the table public.session */
export interface SessionInitializer {
  /** Default value: uuid_generate_v4() */
  id?: SessionId;

  user_id: UserProfileId;

  token: string;

  valid_until: Date;

  /** Default value: CURRENT_DATE */
  created_at?: Date;
}

/** Represents the mutator for the table public.session */
export interface SessionMutator {
  id?: SessionId;

  user_id?: UserProfileId;

  token?: string;

  valid_until?: Date;

  created_at?: Date;
}

export const sessionId = z.string() as unknown as z.Schema<SessionId>;

export const session = z.object({
  id: sessionId,
  user_id: userProfileId,
  token: z.string(),
  valid_until: z.date(),
  created_at: z.date(),
}) as unknown as z.Schema<Session>;

export const sessionInitializer = z.object({
  id: sessionId.optional(),
  user_id: userProfileId,
  token: z.string(),
  valid_until: z.date(),
  created_at: z.date().optional(),
}) as unknown as z.Schema<SessionInitializer>;

export const sessionMutator = z.object({
  id: sessionId.optional(),
  user_id: userProfileId.optional(),
  token: z.string().optional(),
  valid_until: z.date().optional(),
  created_at: z.date().optional(),
}) as unknown as z.Schema<SessionMutator>;
